### ISSUE TITLE
BUG: tcc query-string

### ISSUE THREAD

**Issue by cometwk** [yedf/dtmcli-java#1]
BUG:
FILE: tcc.java

```java
HttpResponse response2 = HttpRequest.post(tryUrl)
                    .body(JSONUtil.toJsonStr(body))
                    .form(paramMap2) // HERE
                    .execute();
```

maybe FIX :

```java
            HttpResponse response2 = HttpRequest.post(tryUrl + "?" + mapToQueryString(paramMap2))
                    .body(JSONUtil.toJsonStr(body))
                    //.form(paramMap2)
                    .execute();

  private static String mapToQueryString(Map<String, Object> queryParams) {
        String queryString = queryParams.entrySet().stream()
                .map(e -> e.getKey() + "=" + e.getValue())
                .collect(Collectors.joining("&"));
        return URLUtil.encode(queryString);
    }
```

**Comment by li-xiao-shuang** [comment]
> BUG: FILE: tcc.java
> 
> ```java
> HttpResponse response2 = HttpRequest.post(tryUrl)
>                     .body(JSONUtil.toJsonStr(body))
>                     .form(paramMap2) // HERE
>                     .execute();
> ```
> 
> maybe FIX :
> 
> ```java
>             HttpResponse response2 = HttpRequest.post(tryUrl + "?" + mapToQueryString(paramMap2))
>                     .body(JSONUtil.toJsonStr(body))
>                     //.form(paramMap2)
>                     .execute();
> 
>   private static String mapToQueryString(Map<String, Object> queryParams) {
>         String queryString = queryParams.entrySet().stream()
>                 .map(e -> e.getKey() + "=" + e.getValue())
>                 .collect(Collectors.joining("&"));
>         return URLUtil.encode(queryString);
>     }
> ```

能详细的描述下具体的问题是什么嘛？例如：
1.报错信息
2.现状
3.预期结果

**Comment by li-xiao-shuang** [comment]
超时没有反馈
